import { Activity, AlertTriangle, Bot, Braces, Clock3, Database, Gauge, Hammer, Layers3, ShieldCheck, Timer, Waypoints } from "lucide-react";

import { EmptyState } from "@/components/ui/empty-state";
import { StatusPill } from "@/components/ui/status-pill";
import type { DashboardSnapshot } from "@/lib/dashboard/queries";
import type { CodexActivityRecord, CodexMeasuredValue, CodexTelemetryBreakdown, CodexTelemetryTimingBreakdown, CodexTelemetryTrendPoint, DataResult } from "@/lib/providers/types";

export function CodexActivityPage({ snapshot }: Readonly<{ snapshot: DashboardSnapshot }>) {
  const t = snapshot.codex;
  if (t.activity.status === "unavailable") return <Page title="Codex Activity" eyebrow="Agents / Codex Activity" description="Operational Codex telemetry from the private relay and D1 provider."><SourceBanner snapshot={snapshot} /><EmptyState description={t.activity.reason} /></Page>;
  const unknown = t.activity.data.filter((event) => event.category === "unknown");
  const relatedTools = connectedTotal(t.tools, (tool) => tool.relatedEventCount);
  const completedTools = connectedTotal(t.tools, (tool) => tool.completedExecutionCount);
  return <Page title="Codex Activity" eyebrow="Agents / Codex Activity" description="Privacy-filtered operational telemetry. Events, executions, and usage are kept distinct; none of these values represent account quota, billing, credits, or cost.">
    <SourceBanner snapshot={snapshot} />
    <div className="mb-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
      <Stat label="Events today" value={t.todayEventCount} /><Stat label="Sessions · 24h" value={t.observedSessionCount24h} />
      <Stat label="Tool-related events · 30d" value={relatedTools} /><Stat label="Completed tool executions · 30d" value={completedTools} />
      <Stat label="Failed executions · 30d" value={t.failedToolCount30d} warning /><Stat label="Approvals · 30d" value={connectedTotal(t.approvals, (x) => x.count)} />
      <Stat label="Errors · 30d" value={trendTotal(t.trends.thirtyDay, "errors")} warning /><Stat label="Unknown recent events" value={unknown.length} />
    </div>
    <div className="grid gap-4 xl:grid-cols-[1.4fr_0.6fr]">
      <Panel title="Recent event timeline" icon={Activity}>{t.activity.data.length ? <div className="space-y-2">{t.activity.data.map((event) => <EventRow event={event} key={event.id} />)}</div> : <EmptyState compact title="No telemetry received" description="D1 is connected but contains no Codex events." />}</Panel>
      <div className="space-y-4"><TrendPanel title="24-hour activity" result={t.trends.twentyFourHour} /><TrendPanel title="30-day activity" result={t.trends.thirtyDay} /><BreakdownPanel title="Event categories" result={t.categories} icon={Layers3} /><BreakdownPanel title="Models observed" result={t.models} icon={Bot} /><BreakdownPanel title="Reasoning effort" result={t.reasoningEfforts} icon={Gauge} /></div>
    </div>
    <div className="mt-4 grid gap-4 xl:grid-cols-3"><ToolPanel snapshot={snapshot} /><TimingPanel title="Event duration" result={t.timings} /><TimingPanel title="TTFT by model" result={t.ttft} /></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-3">
      <BreakdownPanel title="Approval decisions" result={t.approvals} icon={ShieldCheck} /><BreakdownPanel title="Approval policies" result={t.approvalPolicies} icon={ShieldCheck} /><BreakdownPanel title="Sandbox policies" result={t.sandboxPolicies} icon={ShieldCheck} />
      <BreakdownPanel title="MCP servers" result={t.mcpServers} icon={Layers3} /><BreakdownPanel title="MCP origins" result={t.mcpOrigins} icon={Waypoints} /><BreakdownPanel title="Tool namespaces" result={t.toolNamespaces} icon={Hammer} />
      <BreakdownPanel title="Agents" result={t.agents} icon={Bot} /><BreakdownPanel title="Providers" result={t.providers} icon={Database} /><BreakdownPanel title="Originators" result={t.originators} icon={Waypoints} />
      <BreakdownPanel title="App versions" result={t.appVersions} icon={Database} /><BreakdownPanel title="Service versions" result={t.serviceVersions} icon={Database} /><BreakdownPanel title="Startup status" result={t.startupStatuses} icon={Activity} />
    </div>
    <div className="mt-4"><CorrelationPanel snapshot={snapshot} /></div>
    <div className="mt-4 grid gap-4 xl:grid-cols-2"><SessionPanel snapshot={snapshot} /><Panel title="Recent errors and warnings" icon={AlertTriangle}>{t.recentErrors.status === "unavailable" ? <EmptyState compact description={t.recentErrors.reason} /> : t.recentErrors.data.length ? <div className="space-y-2">{t.recentErrors.data.map((event) => <EventRow event={event} key={event.id} />)}</div> : <EmptyState compact title="No warning samples" description="No warning- or error-classified events are present in this window." />}</Panel></div>
    <div className="mt-4"><Panel title="Unknown-event inspector" icon={Braces}>{unknown.length ? <div className="grid gap-2 xl:grid-cols-2">{groupUnknown(unknown).map((group) => <details className="panel-subtle p-3.5" key={group.eventName}><summary className="cursor-pointer text-xs font-medium text-slate-300">{group.eventName} · {group.count.toLocaleString()}</summary><p className="mt-2 text-[10px] leading-5 text-slate-600">Only sanitized unknown key names are retained. Values are discarded before D1.</p><div className="mt-2 flex flex-wrap gap-1.5">{group.keys.map((key) => <span className="rounded-full border border-white/[0.08] px-2 py-1 text-[10px] text-slate-500" key={key}>{key}</span>)}</div></details>)}</div> : <EmptyState compact title="No unknown recent events" description="Every recent event matched a supported operational category." />}</Panel></div>
  </Page>;
}

export function UsagePage({ snapshot }: Readonly<{ snapshot: DashboardSnapshot }>) {
  const t = snapshot.codex;
  return <Page title="Usage" eyebrow="Capacity / Usage" description="Directly emitted token and performance measurements, aggregated without estimating billing, quota, credits, or cost.">
    <SourceBanner snapshot={snapshot} />
    {t.usage.status === "unavailable" ? <EmptyState description={t.usage.reason} /> : <div className="space-y-4">
      <div className="grid gap-4 xl:grid-cols-3">{t.usage.data.map((window) => <Panel key={window.window} title={`${windowLabel(window.window)} usage summary`} icon={Gauge}><div className="grid gap-3 sm:grid-cols-2"><MeasuredStat label="Input tokens" metric={window.inputTokens} /><MeasuredStat label="Output tokens" metric={window.outputTokens} /><MeasuredStat label="Cached/read tokens" metric={window.cachedInputTokens} /><MeasuredStat label="Cache-write tokens" metric={window.cacheWriteTokens} /><MeasuredStat label="Reasoning tokens" metric={window.reasoningTokens} /><MeasuredStat label="Tool tokens" metric={window.toolTokens} /></div><p className="mt-4 text-[10px] leading-5 text-slate-600">{window.eventsWithUsage.toLocaleString()} usage-bearing events · {window.sessionsWithUsage.toLocaleString()} sessions · {window.modelsWithUsage.toLocaleString()} models</p></Panel>)}</div>
      <TokenTrendPanel result={t.trends.twentyFourHour} title="Token trend · 24 hours" /><TokenTrendPanel result={t.trends.thirtyDay} title="Token trend · 30 days" />
      <ModelAnalytics snapshot={snapshot} />
      <ReasoningAnalytics snapshot={snapshot} />
      <div className="grid gap-4 xl:grid-cols-3"><BreakdownPanel title="Reasoning effort" result={t.reasoningEfforts} icon={Gauge} /><TimingPanel title="TTFT by model" result={t.ttft} /><ToolPanel snapshot={snapshot} /></div>
      <SessionPanel snapshot={snapshot} />
    </div>}
    <div className="mt-4 rounded-xl border border-amber-200/15 bg-amber-200/[0.04] p-4 text-xs leading-5 text-amber-100/65">Remaining weekly or five-hour percentage, subscription quota, reset timers, banked resets, billing, credit balance, dollar spend, and internal rate-limit allocations are unavailable and are not inferred. Cache hit percentage is also unavailable because the emitted counters do not establish a defensible denominator.</div>
  </Page>;
}

function ReasoningAnalytics({ snapshot }: Readonly<{ snapshot: DashboardSnapshot }>) {
  const result = snapshot.codex.reasoningAnalytics;
  return <Panel title="Reasoning-effort analytics · 30 days" icon={Gauge}>{result.status === "unavailable" ? <EmptyState compact description={result.reason} /> : result.data.length ? <div className="grid gap-3 xl:grid-cols-2">{result.data.map((item) => <div className="panel-subtle p-4" key={item.reasoningEffort}><div className="flex justify-between gap-3"><p className="text-sm font-medium text-slate-300">{item.reasoningEffort}</p><span className="text-[10px] text-slate-600">{item.sessionCount} sessions</span></div><p className="mt-2 text-[10px] leading-5 text-slate-500">{item.eventCount} events · {item.usageEventCount} usage events · {item.toolExecutions} completed tools · TTFT avg {milliseconds(item.averageTtftMs)} · duration avg {milliseconds(item.averageDurationMs)}</p><p className="mt-2 text-[10px] leading-5 text-slate-600">Input {display(item.inputTokens)} · Output {display(item.outputTokens)} · Cached {display(item.cachedTokens)} · Cache-write {display(item.cacheWriteTokens)} · Reasoning {display(item.reasoningTokens)} · Tool {display(item.toolTokens)}</p></div>)}</div> : <EmptyState compact title="Reasoning effort unavailable" description="No safe reasoning-effort identifier was emitted in this window." />}</Panel>;
}

function CorrelationPanel({ snapshot }: Readonly<{ snapshot: DashboardSnapshot }>) {
  const result = snapshot.codex.correlations;
  if (result.status === "unavailable") return <Panel title="Operational correlations" icon={Waypoints}><EmptyState compact description={result.reason} /></Panel>;
  const groups = new Map<string, typeof result.data>();
  for (const item of result.data) groups.set(item.dimension, [...(groups.get(item.dimension) ?? []), item]);
  return <Panel title="Operational correlations · 30 days" icon={Waypoints}>{groups.size ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[...groups].map(([dimension, items]) => <div className="panel-subtle p-4" key={dimension}><p className="mb-3 text-[10px] font-semibold uppercase tracking-wider text-slate-500">{dimension}</p><div className="space-y-2">{items.slice(0, 10).map((item) => <div className="flex justify-between gap-3 text-[10px]" key={item.label}><span className="truncate text-slate-400">{item.label}</span><span className="text-slate-600">{item.count.toLocaleString()}</span></div>)}</div></div>)}</div> : <EmptyState compact title="No correlation samples" description="The required paired dimensions were not emitted together in this window." />}</Panel>;
}

function ModelAnalytics({ snapshot }: Readonly<{ snapshot: DashboardSnapshot }>) {
  const result = snapshot.codex.modelAnalytics;
  return <Panel title="Model analytics · 30 days" icon={Bot}>{result.status === "unavailable" ? <EmptyState compact description={result.reason} /> : result.data.length ? <div className="grid gap-3 xl:grid-cols-2">{result.data.map((model) => <div className="panel-subtle p-4" key={model.model}><div className="flex items-center justify-between gap-3"><p className="text-sm font-medium text-slate-300">{model.model}</p><span className="text-[10px] text-slate-600">{model.sessionCount.toLocaleString()} sessions</span></div><p className="mt-2 text-[10px] leading-5 text-slate-500">{model.eventCount.toLocaleString()} events · {model.usageEventCount.toLocaleString()} usage events · {model.toolExecutions.toLocaleString()} completed tools · {model.toolFailures.toLocaleString()} failures · {model.approvalEvents.toLocaleString()} approvals</p><p className="mt-2 text-[10px] leading-5 text-slate-600">Input {display(model.inputTokens)} · Output {display(model.outputTokens)} · Cached {display(model.cachedTokens)} · Cache-write {display(model.cacheWriteTokens)} · Reasoning {display(model.reasoningTokens)} · Tool {display(model.toolTokens)}</p><p className="mt-2 text-[10px] text-slate-600">TTFT avg {milliseconds(model.averageTtftMs)} · duration avg {milliseconds(model.averageDurationMs)}</p></div>)}</div> : <EmptyState compact title="No model samples" description="No model identifier was emitted in this window." />}</Panel>;
}

function SessionPanel({ snapshot }: Readonly<{ snapshot: DashboardSnapshot }>) {
  const result = snapshot.codex.sessions;
  return <Panel title="Recent session analytics" icon={Waypoints}>{result.status === "unavailable" ? <EmptyState compact description={result.reason} /> : result.data.length ? <div className="grid gap-2 xl:grid-cols-2">{result.data.map((s) => <div className="panel-subtle p-3.5" key={s.sessionId}><div className="flex items-center justify-between gap-3"><p className="truncate text-xs font-medium text-slate-300">{s.sessionId}</p><span className="text-[10px] text-slate-600">{span(s.firstSeenAt, s.lastSeenAt)}</span></div><p className="mt-1 text-[10px] text-slate-500">{s.models.join(", ") || "Model unavailable"} · {s.reasoningEfforts.join(", ") || "effort unavailable"}</p><p className="mt-1 text-[10px] leading-5 text-slate-600">{s.eventCount} events · {s.usageEvents} usage · {s.toolRelatedEvents} tool-related · {s.toolExecutions} completed · {s.approvalEvents} approvals · {s.errorCount} errors · {s.warningCount} warnings</p><p className="mt-1 text-[10px] leading-5 text-slate-600">Input {display(s.inputTokens)} · Output {display(s.outputTokens)} · Cached {display(s.cachedTokens)} · Cache-write {display(s.cacheWriteTokens)} · Reasoning {display(s.reasoningTokens)} · Tool {display(s.toolTokens)} · TTFT avg {milliseconds(s.averageTtftMs)}</p></div>)}</div> : <EmptyState compact title="No session samples" description="Session analytics require an emitted conversation, session, or thread identifier." />}</Panel>;
}

function ToolPanel({ snapshot }: Readonly<{ snapshot: DashboardSnapshot }>) {
  const result = snapshot.codex.tools;
  return <Panel title="Tool analytics · 30 days" icon={Hammer}>{result.status === "unavailable" ? <EmptyState compact description={result.reason} /> : result.data.length ? <div className="space-y-2">{result.data.map((tool) => <div className="panel-subtle p-3" key={tool.label}><div className="flex justify-between gap-3"><span className="truncate text-xs text-slate-400">{tool.label}</span><span className="text-[10px] text-slate-600">{tool.completedExecutionCount} completed</span></div><p className="mt-1 text-[10px] leading-5 text-slate-600">{tool.relatedEventCount} related events · {tool.successCount} succeeded · {tool.failureCount} failed · failure rate {tool.failureRate === undefined ? "Unavailable" : `${(tool.failureRate * 100).toFixed(1)}%`} · avg {milliseconds(tool.averageDurationMs)} · tool tokens {display(tool.toolTokens)}</p></div>)}</div> : <EmptyState compact title="No tool samples" description="No tool identifiers were emitted in this window." />}</Panel>;
}

function TimingPanel({ title, result }: Readonly<{ title: string; result: DataResult<CodexTelemetryTimingBreakdown[]> }>) {
  return <Panel title={title} icon={Timer}>{result.status === "unavailable" ? <EmptyState compact description={result.reason} /> : result.data.length ? <div className="space-y-2">{result.data.map((x) => <div className="panel-subtle p-3" key={x.label}><div className="flex justify-between gap-3"><span className="text-xs text-slate-400">{x.label}</span><span className="text-[10px] text-slate-600">{x.sampleCount} samples</span></div><p className="mt-1 text-[10px] text-slate-600">avg {milliseconds(x.averageMs)} · p50 {milliseconds(x.p50Ms)} · p95 {milliseconds(x.p95Ms)} · min {milliseconds(x.minimumMs)} · max {milliseconds(x.maximumMs)}</p></div>)}</div> : <EmptyState compact title="No timing samples" description="This measurement was not emitted in the current window." />}</Panel>;
}

function TrendPanel({ title, result }: Readonly<{ title: string; result: DataResult<CodexTelemetryTrendPoint[]> }>) {
  if (result.status === "unavailable") return <Panel title={title} icon={Activity}><EmptyState compact description={result.reason} /></Panel>;
  if (!result.data.length) return <Panel title={title} icon={Activity}><EmptyState compact title="No samples" description="No events fall in this window." /></Panel>;
  const max = Math.max(1, ...result.data.map((x) => x.events));
  return <Panel title={title} icon={Activity}><div className="flex h-24 items-end gap-1 rounded-lg border border-white/[0.06] bg-black/10 px-2 pb-2 pt-3">{result.data.map((x) => <div className="flex h-full min-w-0 flex-1 items-end" key={x.label} title={`${x.label}: ${x.events} events`}><div className="w-full rounded-sm bg-cyan-200/65" style={{ height: `${x.events ? Math.max(10, x.events / max * 100) : 3}%` }} /></div>)}</div><p className="mt-3 text-[10px] text-slate-600">{result.data.reduce((sum, x) => sum + x.events, 0).toLocaleString()} operational events.</p></Panel>;
}

function TokenTrendPanel({ title, result }: Readonly<{ title: string; result: DataResult<CodexTelemetryTrendPoint[]> }>) {
  if (result.status === "unavailable") return <Panel title={title} icon={Gauge}><EmptyState compact description={result.reason} /></Panel>;
  if (!result.data.length) return <Panel title={title} icon={Gauge}><EmptyState compact title="No samples" description="No telemetry falls in this window." /></Panel>;
  const series = [{ key: "inputTokens", label: "Input" }, { key: "outputTokens", label: "Output" }, { key: "cachedTokens", label: "Cached" }, { key: "cacheWriteTokens", label: "Cache-write" }, { key: "reasoningTokens", label: "Reasoning" }, { key: "toolTokens", label: "Tool" }] as const;
  return <Panel title={title} icon={Gauge}><div className="grid gap-2 sm:grid-cols-3 xl:grid-cols-6">{series.map((item) => { const values = result.data.map((point) => point[item.key]); const available = values.some((value) => value !== undefined); const total = values.reduce<number>((sum, value) => sum + (value ?? 0), 0); return <div className="panel-subtle p-3" key={item.key}><p className="text-[10px] uppercase tracking-wider text-slate-600">{item.label}</p><p className="mt-1 text-lg text-slate-200">{available ? total.toLocaleString() : "Unavailable"}</p></div>; })}</div></Panel>;
}

function BreakdownPanel({ title, result, icon }: Readonly<{ title: string; result: DataResult<CodexTelemetryBreakdown[]>; icon: typeof Activity }>) { return <Panel title={title} icon={icon}>{result.status === "unavailable" ? <EmptyState compact description={result.reason} /> : result.data.length ? <div className="space-y-2">{result.data.map((x) => <div className="flex justify-between gap-3 text-xs" key={x.label}><span className="truncate text-slate-400">{x.label}</span><span className="text-slate-600">{x.count.toLocaleString()}</span></div>)}</div> : <EmptyState compact title="No samples" description="No matching field was emitted in this window." />}</Panel>; }
function EventRow({ event }: Readonly<{ event: CodexActivityRecord }>) { const details = [event.eventKind, event.model, event.reasoningEffort, event.toolNamespace && event.toolName ? `${event.toolNamespace}/${event.toolName}` : event.toolName, event.toolExecutionState, event.approvalDecision, event.approvalPolicy, event.sandboxPolicy, event.mcpServer, event.mcpServerOrigin, event.startupPhase, event.startupStatus, event.appVersion, event.ttftMs === undefined ? undefined : `TTFT ${event.ttftMs} ms`, event.durationMs === undefined ? undefined : `${event.durationMs} ms`].filter(Boolean).join(" · "); return <div className="panel-subtle flex items-start gap-3 p-3.5"><div className="mt-0.5 grid size-7 shrink-0 place-items-center rounded-lg border border-white/[0.08] bg-white/[0.035]"><Clock3 size={13} className="text-slate-500" /></div><div className="min-w-0 flex-1"><div className="flex gap-2"><span className="text-[10px] font-semibold uppercase tracking-wider text-cyan-100/60">{event.category}</span><span className="text-[10px] text-slate-600">{formatDate(event.occurredAt)}</span></div><p className="mt-1 truncate text-xs font-medium text-slate-300">{event.eventName}</p><p className="mt-1 truncate text-[10px] text-slate-600">{details || event.sessionId || "No additional safe dimensions emitted"}</p></div></div>; }
function MeasuredStat({ label, metric }: Readonly<{ label: string; metric: CodexMeasuredValue }>) { const value = metric.availability === "available" ? metric.value?.toLocaleString() : metric.availability === "no-samples" ? "No samples" : "Unavailable"; return <div className="panel-subtle p-3"><p className="text-[10px] uppercase tracking-wider text-slate-600">{label}</p><p className="mt-1 text-xl text-slate-100">{value}</p><p className="mt-1 text-[9px] text-slate-700">{metric.sampleCount.toLocaleString()} emitting events</p></div>; }
function SourceBanner({ snapshot }: Readonly<{ snapshot: DashboardSnapshot }>) { const t = snapshot.codex; return <div className="mb-5 flex flex-wrap items-center gap-3 rounded-xl border border-white/[0.08] bg-white/[0.02] px-4 py-3"><StatusPill status={t.health.status} /><span className="text-xs text-slate-500">D1 retention: {t.retentionDays} days</span><span className="text-xs text-slate-600">Last received: {t.lastReceivedAt ? formatDate(t.lastReceivedAt) : "No events received"}</span><span className="ml-auto inline-flex items-center gap-1.5 text-[10px] uppercase tracking-wider text-slate-600"><ShieldCheck size={13} /> Privacy-filtered before persistence</span></div>; }
function Page({ title, eyebrow, description, children }: Readonly<{ title: string; eyebrow: string; description: string; children: React.ReactNode }>) { return <div className="fade-in-up mx-auto max-w-[1380px]"><section className="mb-8"><p className="mb-3 text-[11px] font-semibold uppercase tracking-[0.24em] text-cyan-200/70">{eyebrow}</p><h1 className="page-title text-[42px] font-semibold leading-[1.06] tracking-[-0.055em] text-slate-100">{title}</h1><p className="mt-4 max-w-3xl text-[15px] leading-7 text-slate-400">{description}</p></section>{children}</div>; }
function Panel({ title, icon: Icon, children }: Readonly<{ title: string; icon: typeof Activity; children: React.ReactNode }>) { return <section className="panel p-5 sm:p-6"><div className="mb-5 flex items-center gap-2.5"><Icon size={15} className="text-slate-500" /><h2 className="text-sm font-semibold text-slate-300">{title}</h2></div>{children}</section>; }
function Stat({ label, value, warning }: Readonly<{ label: string; value?: number; warning?: boolean }>) { return <div className="panel p-4"><p className="text-[10px] font-semibold uppercase tracking-wider text-slate-600">{label}</p><p className={`mt-2 text-2xl font-semibold ${warning && value ? "text-amber-100/90" : "text-slate-100"}`}>{value === undefined ? "Unavailable" : value.toLocaleString()}</p></div>; }
function connectedTotal<T>(result: DataResult<T[]>, select: (item: T) => number) { return result.status === "connected" ? result.data.reduce((sum, item) => sum + select(item), 0) : undefined; }
function trendTotal(result: DataResult<CodexTelemetryTrendPoint[]>, key: "errors") { return result.status === "connected" ? result.data.reduce((sum, point) => sum + point[key], 0) : undefined; }
function groupUnknown(events: CodexActivityRecord[]) { const groups = new Map<string, { eventName: string; count: number; keys: Set<string> }>(); for (const event of events) { const group = groups.get(event.eventName) ?? { eventName: event.eventName, count: 0, keys: new Set<string>() }; group.count++; event.unknownAttributeKeys.forEach((key) => group.keys.add(key)); groups.set(event.eventName, group); } return [...groups.values()].map((group) => ({ ...group, keys: [...group.keys].sort() })); }
function display(value?: number) { return value === undefined ? "Unavailable" : value.toLocaleString(); }
function milliseconds(value?: number) { return value === undefined ? "Unavailable" : `${value.toLocaleString(undefined, { maximumFractionDigits: 1 })} ms`; }
function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? "Time unavailable" : new Intl.DateTimeFormat("en", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(date); }
function span(first: string, last: string) { const value = new Date(last).getTime() - new Date(first).getTime(); if (!Number.isFinite(value) || value < 0) return "Span unavailable"; if (value < 60_000) return `${Math.round(value / 1000)}s span`; if (value < 3_600_000) return `${Math.round(value / 60_000)}m span`; return `${(value / 3_600_000).toFixed(1)}h span`; }
function windowLabel(value: "24h" | "7d" | "30d") { return value === "24h" ? "Last 24 hours" : value === "7d" ? "Last 7 days" : "Last 30 days"; }
